### ISSUE TITLE
Refactoring for UI uniformity

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [coding-blocks/amoeba-frontend-server#12]
The Home, All Courses, and About course pages have different UI schemes, making the UI inconsistent.
Some issues caught the eye too.
Examples follow

@abhishek97

**Comment by VibhorCodecianGupta** [comment]
The Homes page looks like this

![screen shot 2018-08-08 at 7 12 46 pm](https://user-images.githubusercontent.com/29275810/43912291-7061423c-9c1f-11e8-9554-52b8b6968bb5.png)

![screen shot 2018-08-08 at 7 13 13 pm](https://user-images.githubusercontent.com/29275810/43912292-70a0d9b0-9c1f-11e8-8778-c6cdf1f33bc1.png)

**Comment by VibhorCodecianGupta** [comment]
**Some Issues**

The mentor picture breaks for `mentors > 2`

![screen shot 2018-08-08 at 7 15 11 pm](https://user-images.githubusercontent.com/29275810/43912646-7613695c-9c20-11e8-8606-e2e118588f16.png)

In the all courses page, the runs displayed are very confusing in the sense that one has difficulty figuring out where the information for a run starts and where does it end. This is because firstly there is no line break between them, and secondly the footer separating line is intuitively in the wrong place, it should more aptly be after the info of a run.

![screen shot 2018-08-08 at 7 37 58 pm](https://user-images.githubusercontent.com/29275810/43912739-bd8beb24-9c20-11e8-9f3d-c4f1e678ecc9.png)

**Comment by VibhorCodecianGupta** [comment]
This looks like a pretty urgent to-do in the sense that the application doesn't look uniform right now, which affects the UX

**Comment by VibhorCodecianGupta** [comment]
Also, the nav-bar and headers in Home and Course id pages are not consistent with the All Courses page, neither the alignment, the text or the spacing.

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 any updates?

**Comment by abhishek97** [comment]
Accepted. Added Bounty.

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 reviews for #13 ?
