### ISSUE TITLE
Add meta tags 

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/amoeba-frontend-server#17]
We currently only have very basic meta tags, we need more tags for better preview cards on twitter, facebook, whatsapp etc.

One way to do so, is to look at source of popular website like stackoverflow and specify those tags here

**Comment by silent-lad** [comment]
OpenGraph meta tags are already there in cookHtml function. and they are also used while rendering.
I'm confused.

**Comment by rakshitkumarcse** [comment]
> OpenGraph meta tags are already there in cookHtml function. and they are also used while rendering.
> I'm confused.

Same question.

**Comment by abhishek97** [comment]
Updated the issue for clarity

**Comment by suyashdeshpande** [comment]
@abhishek97 please review #18

**Comment by abhishek97** [comment]
Closed in #18
